name: continous-deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Deploy stack
        env:
          GANDI_V5: ${{ secrets.GANDI_V5 }}
          ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
          DOCKER_CACERT: ${{ secrets.DOCKER_CACERT }}
          DOCKER_CERT: ${{ secrets.DOCKER_CERT }}
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_TLS_VERIFY: 1
        run: |
          mkdir --parents ~/.docker $HOME/.secrets
          echo "$DOCKER_CACERT" > ~/.docker/ca.pem
          echo "$DOCKER_CERT" > ~/.docker/cert.pem
          echo "$DOCKER_KEY" > ~/.docker/key.pem
          echo "$GANDI_V5" > $HOME/.secrets/gandi_v5
          echo "$ACME_EMAIL" > $HOME/.secrets/acme_email
          docker stack deploy --prune --compose-file ./stack/docker-compose.yml reverse
